version: 2.1
orbs:
  slack: circleci/slack@5.0

jobs:
  notify:
    docker:
      - image: cimg/base:current
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here \n:zap: Start: Visual Testing in Appetiser site."
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }
          event: always

  cypress-tests:
    docker:
      - image: cimg/node:18.20.5
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-{{ .Branch }}
            - npm-cache-
      - run:
          name: Install dependencies and setup environment
          command: |
            npm ci --prefer-offline --no-audit
            sudo apt-get update && sudo apt-get install -y xvfb libnss3 libatk-bridge2.0-0 libgtk-3-0 libxss1 libasound2 libgbm-dev libxshmfence1 libdrm2 libxcomposite1 libxcursor1 libxi6 libxtst6 libnss3-dev
            echo 'pcm.!default { type hw; card 0; }
            ctl.!default { type hw; card 0; }' > ~/.asoundrc
      - save_cache:
          paths:
            - ~/.npm
            - node_modules
          key: npm-cache-{{ checksum "package-lock.json" }}
      - slack/notify:
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here \n🚧 Running: Visual Testing in Appetiser site."
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }
      - run:
          name: Run Cypress tests with Percy
          command: |
            export PERCY_TOKEN="web_673afcf23af14031fd7eb66032b1f4adaa7eb5edfa9da63f16578ae528b284ee"
            npx percy exec -- cypress run --spec "cypress/e2e/daily-test/*/*"
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here \n✅ Success: Percy Visual Testing in Appetiser site."
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Percy Visual Testing Result",
                        "emoji": true
                      },
                      "value": "percy_url",
                      "url": "https://percy.io/faddbeae/web/appetiser-cypress-2aa71831",
                      "action_id": "button-action"
                    }
                  ]
                },                
                { "type": "divider" }
              ]
            }
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here \n❌ Failed: Percy Cypress Testing in Appetiser site."
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Percy Visual Testing Result",
                        "emoji": true
                      },
                      "value": "percy_url",
                      "url": "https://percy.io/faddbeae/web/appetiser-cypress-2aa71831",
                      "action_id": "button-action"
                    }
                  ]
                },                
                { "type": "divider" }
              ]
            }

workflows:
  cypress-workflow:
    jobs:
      - notify:
          context: slack-secrets
      - cypress-tests:
          context: slack-secrets
          requires:
            - notify